### ISSUE TITLE
Kibana 4 released today, your project needs to be updated.

### ISSUE THREAD

**Issue by pofican** [timroes/kibana4-vagrant#2]
They just released Kibana 4 today, I think it is better if you update the repositories accordingly cause Kibana 3 and Kibana 4 Beta are now removed.
Here is the link:
http://www.elasticsearch.org/overview/kibana/installation/

**Comment by timroes** [comment]
I am already on it. Unfortunately something went wrong with their release build, so the 64 bit version is broken at the moment: https://github.com/elasticsearch/kibana/issues/3100

As soon as a working release exist I will upload a new version.

**Comment by pofican** [comment]
I was just going to give it a try, I am holding on for now then... Thanks for the heads up.

**Comment by timroes** [comment]
Something got terribly mixed up here when trying to download all the packages. Actually it was not Kibana that was broken, but my download scripts (which was anyway way more likely :D). So I just updated the repo to include the Kibana 4 release.

**Comment by pofican** [comment]
OK great thanks!
