### ISSUE TITLE
Broken kibana 4.0.2 archives

### ISSUE THREAD

**Issue by PavelVinogradov** [timroes/kibana4-vagrant#3]
Current repository contains broken kibana 4.0.2 archives:

> Downloads>md5sum.exe kibana-4.0.2-linux-x64.tar.gz
> 64d8adf3b25dd382803bc041cca5ea46 *kibana-4.0.2-linux-x64.tar.gz
> 
> kibana4-vagrant\provisioning\files>md5sum.exe kibana-4.0.2-linux-x64.tar.gz
> 8c4dd090cc7007cbf8ae649ccee85cc8 *kibana-4.0.2-linux-x64.tar.gz

**Comment by timroes** [comment]
Just checked. That's true. In my local repository they have the right checksum, but checking out from GitHub I can confirm the wrong checksum. Will try to figure out, what got broken (and how to fix it, since I just can't push another time, but have the right repo locally).

**Comment by timroes** [comment]
Seems to be fixed. Cause was the broken .gitattributes file, I just removed again (it should have anyway been redundant with the perl script in the kibana provisioning file).
