### ISSUE TITLE
Can we get root access to this machine to tweak it?

### ISSUE THREAD

**Issue by vwroad87** [timroes/kibana4-vagrant#4]
All said above.

**Comment by timroes** [comment]
Yes, you can.

`vagrant ssh` in the directory where you checked it out to get a shell into the machine.

Inside the machine you can just use `sudo` without needing a password to do whatever you like.

**Comment by vwroad87** [comment]
It's asking for a username and password?

?

**Comment by timroes** [comment]
Which of the commands (and what exactly did you write)? It should not do this actually.

You could try vagrant/vagrant, but still there seems something wrong (and I could not reproduce this, even with a newly checked out version).

**Comment by vwroad87** [comment]
unfortunately I have to use putty to connect and you are correct!  vagrant
vagrant, should have thought of that!

thanks so much for your help and tutorials

dp
